apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: prod

bases:
  - ../../base

resources:
  - secret.yaml
  - pvc.yaml

patches:
  - patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: cloring-web
      spec:
        replicas: 2
        template:
          spec:
            containers:
              - name: cloring-web
                image: cloring-web:prod
                resources:
                  requests:
                    cpu: "200m"
                    memory: "256Mi"
                  limits:
                    cpu: "1000m"
                    memory: "512Mi"
