apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloring-postgresql
  labels:
    app: cloring-postgresql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloring-postgresql
  template:
    metadata:
      labels:
        app: cloring-postgresql
    spec:
      containers:
        - name: postgresql
          image: {{ .Values.postgresql.image }}
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: cloring-pg-secret
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: cloring-pg-secret
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: cloring-pg-secret
                  key: POSTGRES_DB
          resources:
            requests:
              cpu: {{ .Values.resources.requests.cpu | quote }}
              memory: {{ .Values.resources.requests.memory | quote }}
            limits:
              cpu: {{ .Values.resources.limits.cpu | quote }}
              memory: {{ .Values.resources.limits.memory | quote }}
          volumeMounts:
            - name: pg-data
              mountPath: /var/lib/postgresql/data
          livenessProbe:
            exec:
              command: ["pg_isready", "-U", "$(POSTGRES_USER)"]
            initialDelaySeconds: 15
            periodSeconds: 10
          readinessProbe:
            exec:
              command: ["pg_isready", "-U", "$(POSTGRES_USER)"]
            initialDelaySeconds: 5
            periodSeconds: 5
      volumes:
        - name: pg-data
          {{- if .Values.persistence.enabled }}
          persistentVolumeClaim:
            claimName: cloring-pg-pvc
          {{- else }}
          emptyDir: {}
          {{- end }}
